apiVersion: apps/v1
kind: Deployment
metadata:
  name: alo-doutor
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: alo-doutor
  template:
    metadata:
      labels:
        app: alo-doutor
    spec:
      containers:
        - name: alo-doutor
          image: fbiopereira/alo-doutor:latest
          env:
          - name: ASPNETCORE_HTTP_PORTS
            value: "4141"
          - name: "aspnetcore_environment"
            value: "Release"
          - name: "ConnectionString"
            value: "Server=sql-server;Database=AloDoutor;User ID=sa;Password=P@ssw0rd;Trusted_Connection=False; TrustServerCertificate=True;MultipleActiveResultSets=True"
          ports:
            - containerPort: 4141
---
apiVersion: v1
kind: Service
metadata:
  name: alo-doutor
spec: 
  selector:
    app: alo-doutor
  ports:
    - port: 80
      targetPort: 4141      
  type: ClusterIP